config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  resources :users 

  get "/login", to: "users#login"
  post "/loginresult", to: "users#loginresult"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	validates :password, confirmation: true
	validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
	validates :firstname, :lastname, length: { maximum: 30 }
	validates :age, :phone, numericality:{ :only_integer => true }
	validates :email, :phone,  uniqueness: true
	validates :password, :email, :phone, :firstname, :age, presence:true
	validates :gender, inclusion: %w(male female)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	if session[:id] !=nil
  	@user = User.find(session[:id])
  end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :user_session, except: [:new, :create, :login, :loginresult]

	def new
		@user=User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
		redirect_to root_path
	else
		render 'new'
	end
	end

	def login
	end

	def loginresult
		pp @user = User.find_by_email_and_password(params[:users][:email],params[:users][:password])
		if @user !=nil
			session[:id] = @user.id
			redirect_to user_path(@user.id)
		end
	end

	def show
	end

def destroy
	session[:id] = nil
	redirect_to root_path
end

def edit
end

def update
	@user.update(user_params)
	redirect_to user_path(@user.id)
	end

private 

def user_params
	params.require(:user).permit(:lastname, :firstname, :password, :email, :phone, :age, :country, :city, :street, :adress, :link, :avatar, :gender)
 end

def user_session
	@user = User.find(session[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myproject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% if @user == nil %>
<p><%= link_to "Sign up", new_user_path %> | <%= link_to "Sign in", login_path %></p>
<% else %>
<p><%= link_to "Profile", user_path(@user.id)  %> | <%= link_to "Sign out", user_path(@user.id), method: :delete %></p>
<% end %>

<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/users/edit.html.erb
<%= form_for @user, method: :patch do |f| %>
 
  <p><%= f.label :avatar %></p>
  <%= f.file_field :avatar %><br />

  <p><%= f.label "First name" %></p>
  <%= f.text_field :firstname %><br />

  <p><%= f.label "Last name" %></p>
  <%= f.text_field :lastname %><br />

  <p><%= f.label "Gender" %></p>
  <%= f.select :gender, ['male','female'] %><br />
 
 <p><%= f.label "E-mail" %></p>
  <%= f.text_field :email %><br />

 <p><%= f.label "Password" %></p>
  <%= f.password_field :password %><br />

  <p><%= f.label "Phone" %></p>
  <%= f.text_field :phone %><br />

  <p><%= f.label "Age" %></p>
  <%= f.text_field :age %><br />

<p><%= f.label "Country" %></p>
  <%= f.text_field :country %><br />

  <p><%= f.label "City" %></p>
  <%= f.text_field :city %><br />

  <p><%= f.label "Street" %></p>
  <%= f.text_field :street %><br />
  
  <p><%= f.label "Adres" %></p>
  <%= f.text_field :adress %><br />

  <p><%= f.label "Link" %></p>
  <%= f.text_field :link %><br />

  <p><%= f.submit "Save" %></p>
<% end %>

app/views/users/login.html.erb
<%= form_for :users, url:loginresult_path do |f| %>
 <p><%= f.label "E-mail" %></p>
  <%= f.text_field :email %><br />

 <p><%= f.label "Password" %></p>
  <%= f.password_field :password %><br />

  <p><%= f.submit "Login" %></p>
<% end %>

app/views/users/new.html.erb
<%= form_for :user, url:users_path do |f| %>
<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |msg| %>
	<p><%= msg %></p>
	<% end %>
<% end %>

  <p><%= f.label "First name" %></p>
  <%= f.text_field :firstname %><br />

  <p><%= f.label "Last name" %></p>
  <%= f.text_field :lastname %><br />

  <p><%= f.label "Gender" %></p>
  <%= f.select :gender, ['male','female'] %><br />

 <p><%= f.label "E-mail" %></p>
  <%= f.text_field :email %><br />

 <p><%= f.label "Password" %></p>
  <%= f.password_field :password %><br />

  <p><%= f.label "Phone" %></p>+
  <%= f.text_field :phone %><br />

  <p><%= f.label "Age" %></p>
  <%= f.text_field :age %><br />

<p><%= f.label "Country" %></p>
  <%= f.text_field :country %><br />

  <p><%= f.label "City" %></p>
  <%= f.text_field :city %><br />

  <p><%= f.label "Street" %></p>
  <%= f.text_field :street %><br />
  
  <p><%= f.label "Adress" %></p>
  <%= f.text_field :adress %><br />

  <p><%= f.label "Link" %></p>
  <%= f.text_field :link %><br />

  <p><%= f.label :avatar %></p>
  <%= f.file_field :avatar %>

  <p><%= f.submit "Save" %></p>
<% end %>

app/views/users/show.html.erb
<h1>Hello, <%= @user.firstname %>!</h1>
<p> Here is your params</p>
<%= image_tag @user.avatar.url(:medium) %><br>
<p>Your name: <%= @user.firstname %></p>
<p>Your lastname: <%= @user.lastname %></p>
<p>Your e-mail: <%= @user.email %></p>
<p>Your gender: <%= @user.gender %></p>
<p>Your phone: <%= @user.phone %></p>
<p>Your age: <%= @user.age %></p>
<p>Your country: <%= @user.country %></p>
<p>Your city: <%= @user.city %></p>
<p>Your street: <%= @user.street %></p>
<p>Your adress: <%= @user.adress %></p>
<p>Your link: <%= @user.link %></p>

<%= link_to "Home", root_path %>
<%= link_to "Edit Profile", edit_user_path %>